stages:
  prepare_dataset:
    cmd: python cml_scripts/prepare_dataset.py
    deps:
      - cml_scripts/prepare_dataset.py
      - data/data.csv.gz
    outs:
      - data/sequences.pickle

  train_model:
    cmd: PYTHONPATH=. python cml_scripts/train_model.py
    deps:
      - app/src/
      - data/sequences.pickle
    params:
      - project_name
      - dataloader.num_workers
      - train.epochs
      - train.batch_size
      - train.train_size_ratio
    outs:
      - model_checkpoints/

  run_predictions:
    cmd: python cml_scripts/evaluate_metrics.py
    deps:
    - cml_scripts/evaluate_metrics.py
    metrics:
    - cml_scripts/metrics.json:
        cache: false
