stages:
  unzip_dataset:
    cmd: python cml_scripts/unzip_dataset.py
    deps:
      - cml_scripts/unzip_dataset.py
      - data/data.csv.gz
    outs:
      - data/data.csv
  run_predictions:
    cmd: python cml_scripts/evaluate_metrics.py
    deps:
    - cml_scripts/evaluate_metrics.py
    metrics:
    - cml_scripts/metrics.json:
        cache: false