stages:
  prepare_dataset:
    cmd: python cml_scripts/prepare_dataset.py
    deps:
      - cml_scripts/prepare_dataset.py
      - data/data.csv.gz
    outs:
      - data/sequences.pickle
  run_predictions:
    cmd: python cml_scripts/evaluate_metrics.py
    deps:
    - cml_scripts/evaluate_metrics.py
    metrics:
    - cml_scripts/metrics.json:
        cache: false