stages:
  prepare_dataset:
    cmd: python cml_scripts/prepare_dataset.py
    deps:
      - cml_scripts/prepare_dataset.py
      - data/data.csv.gz
    outs:
      - data/sequences.pickle

  train_model:
    cmd: python -m cml_scripts.train_model
    deps:
      - cml_scripts/train_model.py
      - data/sequences.pickle
    params:
      - project_name
      - dataloader.num_workers
      - train.epochs
      - train.batch_size
      - train.train_size_ratio
    outs:
      - checkpoints/

  validate_model:
    cmd: python -m cml_scripts.evaluate_metrics
    deps:
      - cml_scripts/evaluate_metrics.py
    params:
      - project_name
      - dataloader.num_workers
      - train.epochs
      - train.batch_size
      - train.train_size_ratio

  save_model_from_last_checkpoint_as_state_dict:
    cmd: >-
      python -m 
      cml_scripts.save_model_from_last_checkpoint_as_state_dict
    deps:
      - '${checkpoints_dir}'
    params:
      - checkpoints_dir
      - best_model_save_path
      - dataloader
      - train.epochs
    outs:
      - '${best_model_save_path}'

