project_name: "Recommendation-With-Transformers"

checkpoints_dir: "checkpoints/"

best_model_save_path: "model_state_dicts/bert_model.pth"


dataloader:
  num_workers: 4

train:
  epochs: 1
  batch_size: 256
  train_size_ratio: 0.9
