project_name: "Recommendation-With-Transformers"

checkpoints_dir: "checkpoints/"

dataloader:
  num_workers: 0

train:
  epochs: 5
  batch_size: 256
  train_size_ratio: 0.9

baseline:
  n_neighbors: 100
  data_part: 0.0001


neighbours_checkpoints_dir: "checkpoints_neighbours/"
train_neighbours:
  epochs: 100
  batch_size: 512
